function output = stepResponse(t,G0,Omega,Xi)
    output = -(1/(2.*sqrt((-1 + Xi^2).*Omega^2))).*exp(-t.*(Xi.*Omega + sqrt((-1 + Xi^2).*Omega^2))).*...
        G0.*((-1 + exp(2.*t.*sqrt((-1 + Xi^2).*Omega^2))).*Xi.*Omega + (1 + exp(2.*t.*sqrt((-1 + Xi^2).*Omega^2)) -... 
       2.*exp(t.*(Xi.*Omega + sqrt((-1 + Xi^2).*Omega^2)))).*sqrt((-1 + Xi^2).*Omega^2));
end